### ISSUE TITLE
Require node 18  if no node 16 tests

### ISSUE THREAD

**Issue by mcm1957** [HGlab01/ioBroker.apg-info#103]
Please adapt package.json to require node 18 as you decided to drop node 16 tests.

Thanks

P.S. if I missed something please ignore issue. The goal is that adapter is tested at all installable releasrs of node.

**Comment by HGlab01** [comment]
IT is not the case
I just tried to understand why the integration tests fails starting by today and onge guess was, taht Node16 coudl be the issue.
Bzt as it is a issue with nightly controller build (https://discord.com/channels/743167951875604501/743171252377616476/1156110252136206356) I will not merge this branch and delte it as soon as the controler issue is fixed.

**Comment by mcm1957** [comment]
Ok thanks for info

Tests fail due to error at nightly js-controller build. Foxriver is working on it.
