### ISSUE TITLE
Support additional market (Suisse)

### ISSUE THREAD

**Issue by DoubleG88** [HGlab01/ioBroker.apg-info#208]
Guten Tag

Lange suche und versuche ich von Epex Spot Daten in mein Smart-Home zu integrieren, leider erfolglos. Heute bin ich auf dem Adapter gestossen und dachte ich frage mal höflich nach. :-)

Ist es euch möglich auch andere Länderpreise zu integrieren?
Konkret wünsche ich mir die Preise der Schweiz.

Vielen Dank für eure Antwort
Freundliche Grüsse
Guntz Gael

**Comment by HGlab01** [comment]
Fragen kostet ja bekanntlich nichts :-)
Kennst du eine Quelle wo man die CH Daten bekommt?
Bestenfalls ein API; eventuell sonst auch eine Homepage, die die Daten liefert

**Comment by DoubleG88** [comment]
Ja, ein Versuch ist es Wert. :-)

Epex Spot liefert die Preise auf der Webseite.
Hier der link mit CH Preisen: 
https://www.epexspot.com/en/market-data?market_area=CH&trading_date=2024-04-04&delivery_date=2024-04-05&underlying_year=&modality=Auction&sub_modality=DayAhead&technology=&product=60&data_mode=table&period=&production_period=

Ich bin mir nicht sicher ob sie eine API haben oder ob sie nur Schnittstellen für Händler bieten.
Danke schon mal fürs abklären.

**Comment by HGlab01** [comment]
Hallo! Ich hab eine Quelle für CH gefunden und arbeite an einer Implementierung...
Mal so zur Info...

Du kannst auch mit
`iobroker url HGlab01/ioBroker.apg-info#f294940ac86b9d636b2cc34752b735f82d6de72f`
eine sehr frühe Version antesten. Eigentlich sollten die CH Werte da schon mal aufscheinen

**Comment by DoubleG88** [comment]
Hallo

Wow, das wäre ja Super! :-)
Ich schaue demnächst bei der Beta >Version mal rein. :-)
Da wird sich mein Kollege auch freuen. 

Danke schon mal und Gruss
Gael

**Comment by HGlab01** [comment]
Noch ist es nicht implementiert...
Aber du kannst dich mal über (rechts oben Login und dann registrieren)
https://transparency.entsoe.eu/
registrieren und dann per email an 
transparency@entsoe.eu
mit dem Inhalt in etwa wie
I would like to get RESTFUL API access.
My registered e-mail address is [email address]

Den Token denn du danach generieren kannst, brauchst du für den Zugang.
Bei mir hat der Request ohne Probleme und rasch funktioniert.

**Comment by HGlab01** [comment]
Version zum Testen ist da
am besten über die Console mit
`iob upgrade iobroker.apg-info@0.1.8-alpha.0`

**Comment by DoubleG88** [comment]
Hab die Version upgedated. Soweit funktioniert.
Hab auch den api Key angefragt und warte nun auf diesen.

Melde mich wenn ich ihn erhalten habe.

Erstmal vielen Dank für die Mühe und Arbeit.

**Comment by HGlab01** [comment]
update to alpha.1

`iob upgrade iobroker.apg-info@0.1.8-alpha.1`

**Comment by DoubleG88** [comment]
Habe das neue Update durchgeführt und den API Key erhalten und eingefügt.
Funktioniert und habe die richtigen Werte.
Ich schaue die Tage ob sie sich auch aktualisieren.

Vielen Dank

**Comment by HGlab01** [comment]
klingt ja vielversprechend ;-)
der Cron-Job ist standardmäßig auf 00.00 und 15.00 eingestellt
Die 00.00 sind ein Must, sollten nach 15.00 die Werte für den nächsten Tag noch nicht da sein, kannst du mal mit den 15.00 Uhr spielen und auf zB 20.00 stellen.
Aber die Börsenpreise sind eigentlich bis 15.00 alle fixiert und sollten daher auch veröffentlicht sein

**Comment by HGlab01** [comment]
any news?

**Comment by DoubleG88** [comment]
Hab jetzt seit es läuft wöchendlich bis täglich reingeschaut. funktioniert sehr gut. :-)
Einzig, die Thomorow daten zeigen 0 an. Stört mich aber nicht, da ich die tagesaktuellen Werte nutze.

Vielen Dank an dieser Stelle.

**Comment by HGlab01** [comment]
wann startet die Abfrage?
Dann läuft sie zu früh und die Daten sind noch nicht da

**Comment by DoubleG88** [comment]
Ist auf 0:55 und 15:55 gestellt.
Hab den Adapter neu gestartet und jetzt sind die Werte drinn.
Hab jetzt mal auf 17:55 gestellt und schau ob er sie jetzt zuverlässig erhält.

**Comment by HGlab01** [comment]
00:55 ist ein wenig gefährlich, da die Werte bei Today dann bis 0:55 vom Vortag stehen; stell denn lieber auf 00:00

**Comment by HGlab01** [comment]
Swiss market supported in https://github.com/HGlab01/ioBroker.apg-info/releases/tag/v0.1.8
