### ISSUE TITLE
Object containing the Date

### ISSUE THREAD

**Issue by noriyuki41** [HGlab01/ioBroker.apg-info#226]
It would be helpful if today and tomorrow contain an object showing the date for which the data is valid.
This is especially important because the prices are updated at 3 p.m. Until then tommorow is today?!

**Comment by HGlab01** [comment]
Hey, thanks for the feedback!
Per default the adapter runs at 00:00:05, 13:00:00:05 and 15:00:05 https://github.com/HGlab01/ioBroker.apg-info/blob/6582f2187a3e03a3622a7b8e43dfe592a85d55e7/io-package.json#L153 which means that 5 seconds after midnight the new day changes to today. The run at view seconds after midnight is highly recommended.
Nevertheless adding a attribute with the date to which date the objects belong can be implemented. Will take care about

**Comment by HGlab01** [comment]
apg-info.0.marketprice.today.date
apg-info.0.marketprice.tomorrow.date
implemented in 0.1.7-apha.1

Can be tested with
`iob upgrade iobroker.apg-info@0.1.7-alpha.1`
